INFO 2023-06-29 10:59:23,326 views 33716 140136528475904 api_sms_pay 

INFO 2023-06-29 10:59:23,345 views 33716 140136528475904 ERROR: Traceback (most recent call last):
  File "/home/main/Desktop/natruda/shawarma_quene/shawarma3/python3-shawarma/shaw_queue/views.py", line 7085, in api_sms_pay
    order_items = list(json.loads(order_items))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 

INFO 2023-06-29 11:07:09,930 views 33716 140136503297792 api_sms_pay 

INFO 2023-06-29 11:07:09,943 views 33716 140136503297792 ERROR: Traceback (most recent call last):
  File "/home/main/Desktop/natruda/shawarma_quene/shawarma3/python3-shawarma/shaw_queue/views.py", line 7085, in api_sms_pay
    order_items = list(json.loads(order_items))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 

INFO 2023-06-29 11:07:43,330 views 34376 140234969020160 api_sms_pay 

INFO 2023-06-29 11:07:43,346 views 34376 140234969020160 ERROR: Traceback (most recent call last):
  File "/home/main/Desktop/natruda/shawarma_quene/shawarma3/python3-shawarma/shaw_queue/views.py", line 7085, in api_sms_pay
    order_items = list(json.loads(order_items))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 

INFO 2023-06-29 11:08:52,101 views 34418 140349154588416 api_sms_pay 

INFO 2023-06-29 11:08:52,129 views 34418 140349154588416 ERROR: Traceback (most recent call last):
  File "/home/main/Desktop/natruda/shawarma_quene/shawarma3/python3-shawarma/shaw_queue/views.py", line 7085, in api_sms_pay
    order_items = list(json.loads(order_items))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 

INFO 2023-06-29 11:09:21,828 views 34501 139857351898880 api_sms_pay 

INFO 2023-06-29 11:09:21,856 views 34501 139857351898880 ERROR: Traceback (most recent call last):
  File "/home/main/Desktop/natruda/shawarma_quene/shawarma3/python3-shawarma/shaw_queue/views.py", line 7085, in api_sms_pay
    order_items = list(json.loads(order_items))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 

INFO 2023-06-29 11:09:56,159 views 34523 140623922362112 api_sms_pay 

INFO 2023-06-29 11:09:56,159 views 34523 140623922362112 +7(922)125-88-76 0 

INFO 2023-06-29 11:09:56,176 views 34523 140623922362112 ERROR: Traceback (most recent call last):
  File "/home/main/Desktop/natruda/shawarma_quene/shawarma3/python3-shawarma/shaw_queue/views.py", line 7100, in api_sms_pay
    raise ConnectionError
requests.exceptions.ConnectionError
 

INFO 2023-06-29 11:09:56,177 views 34523 140623922362112 ERROR: Traceback (most recent call last):
  File "/home/main/Desktop/natruda/shawarma_quene/shawarma3/python3-shawarma/shaw_queue/views.py", line 7100, in api_sms_pay
    raise ConnectionError
requests.exceptions.ConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/main/Desktop/natruda/shawarma_quene/shawarma3/python3-shawarma/shaw_queue/views.py", line 7110, in api_sms_pay
    raise ConnectionError
requests.exceptions.ConnectionError
 

